# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Joint_l_elbow_pitch:
    has_velocity_limits: true
    max_velocity: 1.1200000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_l_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 2.27
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_l_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 1.1200000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_l_shoulder_yaw:
    has_velocity_limits: true
    max_velocity: 1.54
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_l_wrist_pitch:
    has_velocity_limits: true
    max_velocity: 1.45
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_l_wrist_roll:
    has_velocity_limits: true
    max_velocity: 1.45
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_l_wrist_yaw:
    has_velocity_limits: true
    max_velocity: 4.4699999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_r_elbow_pitch:
    has_velocity_limits: true
    max_velocity: 1.1200000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_r_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 2.27
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_r_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 1.1200000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_r_shoulder_yaw:
    has_velocity_limits: true
    max_velocity: 1.54
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_r_wrist_pitch:
    has_velocity_limits: true
    max_velocity: 1.45
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_r_wrist_roll:
    has_velocity_limits: true
    max_velocity: 1.45
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_r_wrist_yaw:
    has_velocity_limits: true
    max_velocity: 4.4699999999999998
    has_acceleration_limits: false
    max_acceleration: 0